CREATE TABLE CARGO (
  CODIGO INTEGER NOT NULL,
  NOME VARCHAR(30) NOT NULL,
  PRIMARY KEY (CODIGO)
);

CREATE TABLE DEPARTMENT (
  CODE SERIAL NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (CODE)
);

CREATE TABLE FUNCIONARIO (
  REGISTRO INTEGER NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  SEXO VARCHAR(1) NOT NULL,
  NASCIMENTO DATE NOT NULL,
  USUARIO_FK VARCHAR(30) NOT NULL,
  PRIMARY KEY (REGISTRO),
  FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO(USERNAME)
);

CREATE TABLE USUARIO (
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  ACTIVE BOOLEAN NOT NULL,
  PRIMARY KEY (USERNAME)
);


CREATE SEQUENCE SEQ_DEPARTAMENTO START WITH 1; --gerador de números sequenciais

--consulta o próximo valor da sequence
SELECT nextval('SEQ_DEPARTAMENTO');

