CREATE TABLE CARGO (
  CODIGO INTEGER NOT NULL,
  NOME VARCHAR(30) NOT NULL,
  PRIMARY KEY (CODIGO)
);

CREATE TABLE DEPARTMENT (
  CODE SERIAL NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (CODE)
);
